### ISSUE TITLE
1

### ISSUE THREAD

**Issue by hsl20130659** [zeusees/HyperVID#16]

**Comment by Jinkham** [comment]
@hsl20130659 就是你这种人搞坏了开源，有人说过开源就要效果好是吗？项目提供了数据集，效果不好你自己训练啊，自己没数据？那几说啥？

**Comment by hsl20130659** [comment]
你个傻屌，你还看不出他们开源这个的目的吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JinK ***@***.***&gt;
发送时间: 2022年3月26日 00:26
收件人: zeusees/HyperVID ***@***.***&gt;
抄送: hsl20130659 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [zeusees/HyperVID] 识别模型太垃圾了 (Issue #16)





 
@hsl20130659 就是你这种人搞坏了开源，有人说过开源就要效果好是吗？项目提供了数据集，效果不好你自己训练啊，自己没数据？那几说啥？

**Comment by Jinkham** [comment]
@hsl20130659  就你洪叁亮牛逼是吧？草你妈的，把你在网上发的这些东西发给你们公司看看，他们招了一个什么货色！

**Comment by hsl20130659** [comment]
草你妈逼，怎么骂人了，你以为我是好惹的吗，你去发啊，谁怕谁，开源个垃圾项目算什么东西

**Comment by Jinkham** [comment]
@hsl20130659 妈了个逼的，他妈的这就给你公司行政还有法务发邮件，看他们怎么说，你这种狗杂种不收拾你就是对社会的祸害！草你妈的，你等着麻烦吧。

**Comment by hsl20130659** [comment]
狗杂种，狗东西，藏在背后伤人算什么，有种报上名来面对我，老子奉陪到底，草你妈逼

**Comment by Jinkham** [comment]
@hsl20130659 狗逼玩意，你要是真有种，昨天就别把留言删掉，就你这怂逼还跟我奉陪到底？给你脸还不要了，你把你发的每一条消息都抄送给你的领导同事，让他们看看你这幅嘴脸。

**Comment by hsl20130659** [comment]
你这个狗杂种，简直就是一条疯狗，有种用真面目示人，藏在背后咬人算什么狗逼玩意

**Comment by Jinkham** [comment]
@hsl20130659 狗逼你发的每一条消息我都有记录，删除也没有用，你发的越多越好，全都给你公司发过去，让你继续牛逼。

**Comment by hsl20130659** [comment]
1

**Comment by hu120051** [comment]
？？？
