### ISSUE TITLE
android 问题

### ISSUE THREAD

**Issue by Joll123** [zeusees/HyperVID#4]
Error computing CMake server result.

Check for working C compiler: /home/jhl/SDK/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

Check for working C compiler: /home/jhl/SDK/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works

Detecting C compiler ABI info

Detecting C compiler ABI info - done

Detecting C compile features

Detecting C compile features - done

Check for working CXX compiler: /home/jhl/SDK/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++

Check for working CXX compiler: /home/jhl/SDK/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works

Detecting CXX compiler ABI info

Detecting CXX compiler ABI info - done

Detecting CXX compile features

Detecting CXX compile features - done

Configuring done

怎么解决？

**Comment by panda-lab** [comment]
你用的ndk版本是哪个？

**Comment by Joll123** [comment]
![image](https://user-images.githubusercontent.com/43200569/60378304-1cf08a80-9a53-11e9-9029-7b06e2752086.png)

**Comment by panda-lab** [comment]
尝试用一下ndk16，或者为了验证可以用vs编译src源码测试。原理是利用opencv dnn调用我们训练的mobilenet模型，输入输出做好了，应为没问题。
